---
abstract: 'Add a BUGS pod section for rt.cpan.org'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Module::Signature: 0
  Socket: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100900'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-Section-BugsRT
recommends: {}
requires:
  Moose: 0
  Moose::Autobox: 0
  Pod::Weaver::Role::Section: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Pod-Weaver-Section-BugsRT
  homepage: http://search.cpan.org/dist/Pod-Weaver-Section-BugsRT/
  repository: http://github.com/mschout/pod-weaver-section-bugsrt
version: 0.52
